name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Nodej.js 14.x
        uses: actions/setup-node@master
        with:
          version: 14.x

      - name: Run install dependencies and running tests
        run: |
          npm install
          npm run test:ci

      - name: Coveralls
      uses: coverallsapp/github-action@master    
